"""安装脚本"""
from setuptools import setup, find_packages

setup(
    name="youth-companion-platform",
    version="0.1.0",
    description="基于AI技术的大学生深度社交匹配系统",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn[standard]>=0.24.0",
        "pydantic>=2.5.0",
        "pydantic-settings>=2.1.0",
        "pymysql>=1.1.0",
        "pymongo>=4.6.0",
        "redis>=5.0.1",
        "sqlalchemy>=2.0.23",
        "transformers>=4.35.2",
        "torch>=2.1.1",
        "hypothesis>=6.92.1",
        "pytest>=7.4.3",
        "pytest-asyncio>=0.21.1",
        "pytest-cov>=4.1.0",
        "python-dotenv>=1.0.0",
        "python-multipart>=0.0.6",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
    ],
)
